# Generated by Django 3.2.6 on 2021-08-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20210806_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
