# Generated by Django 3.2.6 on 2021-08-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_subscription_removed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='removed_at',
            new_name='cancelled_at',
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
