# Generated by Django 3.2.6 on 2021-08-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
