# Generated by Django 3.2.6 on 2021-08-13 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_subscription_current_period_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_current_period_end',
        ),
    ]
