# Generated by Django 3.2.6 on 2021-08-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scats',
            name='NB_SCATS_SITE',
            field=models.IntegerField(),
        ),
    ]
