# Generated by Django 3.2.6 on 2021-08-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scats', '0002_alter_scats_qt_interval_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scats',
            name='QT_INTERVAL_COUNT',
            field=models.DateField(),
        ),
    ]
