# Generated by Django 3.2.6 on 2021-08-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Package name, e.g. Package A', max_length=100)),
                ('description', models.TextField(help_text='Description of the product package bundle')),
                ('discount', models.PositiveSmallIntegerField(default=0, help_text='Discount in percentage (0-100)')),
                ('product_items', models.ManyToManyField(to='products.ProductItem')),
            ],
        ),
    ]
